version: "3"
services:
  demo-server-g1: &demo-server
    build:
      context: ..
      dockerfile: demo/Dockerfile
    # image: ghcr.io/jokester/publicaddr:pr-1
    command: npm start
    working_dir: /opt/publicaddr/demo
    deploy:
      replicas: 6
    # NOTE I have no idea how to get default network_mode (requires port mapping) + replica working
    # network_mode=host (and perhaps some other) works with SO_REUSEPORT
    network_mode: host

  # with publicaddr one can even do zero-downtime rollout
  #
  # e.g.
  # 0. Start with g1.replica=6 g2.replica=0  # Users only see reply from g1
  # 1. Set new image in g2
  # 2. Set g1.replicas=3 g1.replicas=3
  # 3. docker-compose up -d                  # user starts to see reply from g1 / g2
  # 4. Set g1.replicas=0 g2.replicas=6
  # 5. docker-compose up -d                  # user starts to see reply from g2
  demo-server-g2:
    <<: *demo-server
    # image: ghcr.io/jokester/publicaddr:pr-1
    deploy:
      replicas: 0
