version: "3"
services:
  # see https://iximiuz.com/en/posts/multiple-containers-same-port-reverse-proxy/ for explanation
  sandbox:
    image: alpine
    command: sleep infinity
    ports:
      - 3000:3000

  demo-server-a: &demo-server
    build: .
    command: publicaddr node /opt/demo-server.mjs
    network_mode: service:sandbox
    environment:
      VERSION: 'a'
    deploy:
      replicas: ${VERSION_A_REPLICA:-4}

  demo-server-b: &demo-server
    build: .
    command: publicaddr node /opt/demo-server.mjs
    network_mode: service:sandbox
    environment:
      VERSION: 'b'
    deploy:
      replicas: ${VERSION_B_REPLICA:-0}
